# fly.toml file generated for blogster on 2022-11-29T16:49:56+02:00

app = "blogster"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "3003"
  MONGOURL = "mongodb+srv://FullStack22:ykhQdPIPM3VbnJ6z@cluster0.chfes.mongodb.net/blogProject?retryWrites=true&w=majority"
  SECRET = "f%sb6P1Mb*t^hTOb9jHsBwWe8BV1wovgr$o7osj@IJGP9o!$WD"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3003
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
